### PR TITLE
sentry: package version downgraded to 1.19.1

### PR DESCRIPTION
**Pull request by DonHaul**

### CODE REVIEW

**Comment by DonHaul** [comment]
Fixes [#512](https://github.com/cern-sis/issues-inspire/issues/512)

**Comment by drjova** [comment]
@DonHaul could you please add the linked issue in the commit message? This way we can easily generate changelog.

```
sentry: package version downgraded to 1.19.1

* ref: cern-sis/issues-inspire/issues/512
```

**Comment by DonHaul** [comment]
For testing it was working  I did the following:
Settings from the `production.py` temporarily copied locally
Created a test route  `/sentry-debug` that would always fail that I removed after
Tested multiple sentry-sdk versions, latest version that is working is `1.19.1`

https://sentry.siscern.org/inspire/backoffice/

**Comment by drjova** [comment]
is the `/sentry-debug` only enabled when DEBUG=True ?

**Comment by DonHaul** [comment]
@drjova I removed the route altogether , should I re add it

**Comment by drjova** [comment]
it's still there, if you like you can remove it https://github.com/inspirehep/backoffice/blob/main/backoffice/config/urls.py#L70

**Review by drjova — APPROVED** [review]

**Pull request merged**
