### PR TITLE
workflowticket serializer: use the serializer in the create function

### LINKED ISSUE #544: Review the WorkflowTicketViewSet create() to use the serializer
Current implementation:
https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/api/views.py#L84

Check serializer implementation:
https://github.com/inspirehep/backoffice/pull/76

### PR DESCRIPTION
**Pull request by DonHaul**
* ref: cern-sis/issues-inspire/issues/544

### CODE REVIEW

**Review by drjova — CHANGES_REQUESTED** [review]
@DonHaul could you please update the commit message?

**Comment by DonHaul** [comment]
@drjova what part of the commit message is wrong?

**Comment by drjova** [comment]
there is no `workflowticket serializer` application in the project, since we have two different applications we should use something like:

``` workflows: add a serializer in the WorkflowTicket create```

**Comment by DonHaul** [comment]
thanks understood.

**Review by drjova — APPROVED** [review]

**Pull request merged**
